### ISSUE TITLE
Block-scope declarations outside strict mode

### ISSUE THREAD

**Issue by Nevon** [jxnblk/repng#1]
```
➜  ui git:(master) repng Button/Primary/index.jsx
/usr/local/lib/node_modules/repng/bin/repng.js:67
  let css
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
➜  ui git:(master) node --version
v5.10.1
```

**Comment by jxnblk** [comment]
You'll need Node v6 or up for repng. I'll add a note in the readme

**Comment by Nevon** [comment]
Put it in the `engines` section of your package.json instead. https://docs.npmjs.com/files/package.json#engines
