### ISSUE TITLE
css loader

### ISSUE THREAD

**Issue by sylvainbannier** [jxnblk/repng#3]
Atempting to render component which load CSS through webpack loader with
`import from "style.css" `
I got this issue : 
```
SyntaxError: /home/user/NewsCard/style.css: Unexpected token (1:0)
> 1 | .NewsCard {
    | ^
  2 |   display:block;
  3 | }
  4 | 
    at Parser.pp$5.raise (/home/user/.npm-packages/lib/node_modules/repng/node_modules/babylon/lib/index.js:4215:13)
    at Parser.pp.unexpected (/home/user/.npm-packages/lib/node_modules/repng/node_modules/babylon/lib/index.js:1599:8)
    at Parser.pp$3.parseExprAtom (/home/user/.npm-packages/lib/node_modules/repng/node_modules/babylon/lib/index.js:3560:12)
    at Parser.parseExprAtom (/home/user/.npm-packages/lib/node_modules/repng/node_modules/babylon/lib/index.js:6307:22)
    at Parser.pp$3.parseExprSubscripts (/home/user/.npm-packages/lib/node_modules/repng/node_modules/babylon/lib/index.js:3305:19)
    at Parser.pp$3.parseMaybeUnary (/home/user/.npm-packages/lib/node_modules/repng/node_modules/babylon/lib/index.js:3285:19)
    at Parser.pp$3.parseExprOps (/home/user/.npm-packages/lib/node_modules/repng/node_modules/babylon/lib/index.js:3215:19)
    at Parser.pp$3.parseMaybeConditional (/home/user/.npm-packages/lib/node_modules/repng/node_modules/babylon/lib/index.js:3192:19)
    at Parser.pp$3.parseMaybeAssign (/home/user/.npm-packages/lib/node_modules/repng/node_modules/babylon/lib/index.js:3155:19)
    at Parser.parseMaybeAssign (/home/user/.npm-packages/lib/node_modules/repng/node_modules/babylon/lib/index.js:5603:20)
```

I guess repng doesn't load CSS imported from component.
Is there any plan to enable that ?

**Comment by jxnblk** [comment]
Only the dev server uses webpack, for actually rendering the image it's just Node, and I probably won't add webpack to the core render function.

You *can* import a template tag/string of css and put it in a style tag – or use the `--css` option.
