### ISSUE TITLE
Requires babel 7

### ISSUE THREAD

**Issue by iamnewton** [jxnblk/repng#32]
Just tried to install this and run an example on a sample lib I have and got this error.  Am I missing something?

```
#1662: $ repng src/funnel/item.js  --width 512 --height 512 --out-dir .
⠋ Rendering src/funnel/item.js/usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/Users/chrisopedia/Code/rubiconproject/legion/components/node_modules/@rubicon/babel-preset/index.js")
    at throwVersionError (/Users/chrisopedia/Code/rubiconproject/legion/components/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/chrisopedia/Code/rubiconproject/legion/components/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/chrisopedia/Code/rubiconproject/legion/components/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:29:7)
    at /Users/chrisopedia/Code/rubiconproject/legion/components/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/local/lib/node_modules/repng/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/usr/local/lib/node_modules/repng/node_modules/babel-register/lib/node.js:103:45)
    at loader (/usr/local/lib/node_modules/repng/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/repng/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)```

**Comment by jxnblk** [comment]
Sorry for the delay. The next major version will use Babel 7
