### ISSUE TITLE
Error when installing: 'Maximum call stack size exceeded' 

### ISSUE THREAD

**Issue by markjackson02** [jxnblk/repng#37]
Console output:
```
$ npm i -g repng
npm WARN deprecated datauri@1.1.0: Datauri 2.0 released. See more in https://github.com/data-uri/datauri/releases/tag/v2.0.0
npm WARN deprecated mimer@0.3.2: Mimer 1.0 released. See more in https://github.com/data-uri/mimer/releases/tag/v1.0.0
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\markj\AppData\Roaming\npm-cache\_logs\2019-05-11T02_05_00_422Z-debug.log
```

Tail of the logs: 
```
3197 verbose stack RangeError: Maximum call stack size exceeded
3197 verbose stack     at RegExp.test (<anonymous>)
3197 verbose stack     at isDepOptional (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:405:45)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:414:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3197 verbose stack     at failedDependency (C:\Users\markj\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:430:9)
3198 verbose cwd C:\Users\markj\workspace\myproject\client
3199 verbose Windows_NT 10.0.17134
3200 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\markj\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "repng"
3201 verbose node v10.14.2
3202 verbose npm  v6.4.1
3203 error Maximum call stack size exceeded
3204 verbose exit [ 1, true ]
```

**Comment by jxnblk** [comment]
Hi! I'm not sure what's happening here, but I suspect it might be an issue with your local setup, npm, or one of the other dependencies. Also looks like you're running on Windows, so I don't have a good way to debug this myself. Can you install other npm packages globally and have you tried using yarn to see if the issue persists?

**Comment by markjackson02** [comment]
Yes, it must be a problem with my local setup or NPM because it installs successfully with Yarn.

Thanks @jxnblk !
